#!/bin/sh
echo "@EMACS"
sleep 3
sudo dnf build-dep emacs
cd
export CC=/usr/bin/gcc && export CXX=/usr/bin/gcc
wget https://gnu.mirror.constant.com/emacs/emacs-30.1.tar.xz
tar -xvf emacs-30.1.tar.xz
cd emacs-30.1
./autogen.sh
./configure --with-dbus --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xft --with-xpm --with-gpm=no --with-imagemagick --with-json --with-xwidgets --with-modules --with-native-compilation=aot --with-pgtk --without-x --without-pop --with-mailutils --prefix=/usr/local
make -j22
sudo make uninstall
cd
sudo rm -rf emacs*
