# ~/.config/hypr/pyprland.toml
[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
command = "kitty --class kitty-dropterm"
class = "kitty-float"
size = "70% 70%"
margin = 50
animation = "fromTop"
unfocus = "hide"

[scratchpads.tuifm]
command = "kitty --class explorer -e yazi"
class = "explorer"
size = "90% 90%"
margin = 50
animation = "fromBottom"
unfocus = "hide"

[scratchpads.tuigit]
command = "kitty --class git-terminal -e lazygit"
class = "thunar"
size = "80% 80%"
margin = 50
animation = "fromTop"
unfocus = "hide"
