#!/bin/bash
echo "Installing System Packages"
sleep 3
sudo dnf install akmod-nvidia xorg-x11-drv-nvidia-cuda xorg-x11-drv-nvidia-power vulkan xorg-x11-drv-nvidia-cuda-libs nvidia-vaapi-driver libva-utils vdpauinfo kernel-core kernel-devel kernel-headers kernel kernel-devel-matched kernel-modules kernel-modules-core kernel-modules-extra gcc make man-db man-pages less groff-base dkms acpid libglvnd-glx libglvnd-opengl libglvnd-devel pkgconfig xorg-x11-server-Xwayland libxcb egl-wayland dnf-automatic copr-selinux dnf-plugins-core fedora-workstation-repositories qt5-qtwayland qt6-qtwayland fdupes xisxwayland setroubleshoot chrony cronie curl pkgconf system-config-language plymouth-theme-spinner PackageKit-command-not-found zip p7zip p7zip-plugins powertop xcur2png tar unzip wget pipx python3-build python3-installer python3-devel distrobox toolbox mesa-vulkan-drivers kmodtool akmods mokutil openssl 

sudo dnf mark user akmod-nvidia
sudo systemctl enable nvidia-{suspend,resume,hibernate}
sudo sh -c 'echo "%_with_kmod_nvidia_open 1" > /etc/rpm/macros.nvidia-kmod'
sudo akmods --kernels $(uname -r) --rebuild
sudo systemctl mask nvidia-fallback.service
