#!/bin/bash
echo "Setting Up Git"
sleep 3
sudo dnf install git-core git-credential-libsecret gnome-keyring subversion git-delta highlight
git config --global user.name "aahsnr"
git config --global user.email "ahsanur041@proton.me"
git config --global credential.helper /usr/libexec/git-core/git-credential-libsecret

git config --global core.preloadindex true
git config --global core.fscache true
git config --global gc.auto 256
