#!/bin/bash
sudo dnf install flatpak
sudo flatpak remote-delete --system fedora
sudo flatpak remote-delete --system flathub-beta
sudo flatpak remote-delete --system flathub
flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

flatpak install flathub com.ticktick.TickTick
flatpak install flathub org.onlyoffice.desktopeditors
flatpak install flathub com.github.tchx84.Flatseal
flatpak install flathub org.js.nuclear.Nuclear
flatpak install flathub tv.kodi.Kodi
flatpak install flathub com.bitwarden.desktop
