#!/bin/bash
echo "Installing Packages from Source"
sleep 3
bash $HOME/fedora-setup/source-builds/emacs
bash $HOME/fedora-setup/source-builds/grub-btrfs
bash $HOME/fedora-setup/source-builds/materialyoucolor
