#!/bin/bash
systemctl --user daemon-reload
systemctl --user enable --now wireplumber.service pipewire-pulse.socket pipewire.socket pipewire-pulse.service pipewire.service hyprpolkitagent hyprpaper hypridle gnome-keyring-daemoin

#atuin.service atuin-maintenance.timer

sudo systemctl enable haveged rngd pmcd pmlogger --now
