#!/bin/bash
echo "Setting up dotfiles"
sleep 5
ln -sv $HOME/.hyprdots/.config/atuin/ $HOME/.config/
ln -sv $HOME/.hyprdots/.config/bat/ $HOME/.config/
ln -sv $HOME/.hyprdots/.config/kitty/ $HOME/.config/
ln -sv $HOME/.hyprdots/.config/lazygit/ $HOME/.config/
ln -sv $HOME/.hyprdots/.config/starship/ $HOME/.config/
ln -sv $HOME/.hyprdots/.config/zsh/ $HOME/.config/
ln -sv $HOME/.hyprdots/.tmux/ $HOME/
ln -sv $HOME/.hyprdots/.tmux.conf $HOME/
ln -sv $HOME/.hyprdots/.zshrc $HOME/
