#!/bin/bash
echo "Installing GTK3/GTK4 theme"
sudo dnf install sassc gtk-murrine-engine gnome-themes-extra ostree libappstream-glib
cd && git clone https://github.com/vinceliuice/Colloid-gtk-theme.git
cd Colloid-gtk-theme
sudo ./install.sh -l --tweaks catppuccin --tweaks normal
cd
sudo rm -rf Colloid-gtk-theme

echo "Installing Icon Theme"
cd
git clone https://github.com/vinceliuice/Colloid-icon-theme.git
cd Colloid-icon-theme
sudo ./install.sh -s catppuccin -t orange
sudo rm -rf Colloid-icon-theme

sudo flatpak override --filesystem=~/.themes
sudo flatpak override --filesystem=~/.local/share/themes
sudo flatpak override --env=GTK_THEME=Colloid-Dark-Catppuccin

stylepak install-system Colloid-Dark-Catppuccin
