#!/bin/bash
echo "Installing DNF groups"
sleep 3
sudo dnf install @base-x @python-science @rpm-development-tools @authoring-and-publishing @c-development @container-management @development-tools @engineering-and-scientific @hardware-support 
