#!/bin/bash
echo "Initial Setup"
sleep 3
sudo cp -R $HOME/fedora-source/preconfigured-files/dnf.conf /etc/dnf/
sudo cp -R $HOME/fedora-source/preconfigured-files/variables.sh /etc/profile.d/

sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
sudo dnf config-manager setopt fedora-cisco-openh264.enabled=1

sudo dnf copr enable atim/lazygit
sudo dnf copr enable atim/starship
sudo dnf copr enable solopasha/hyprland
sudo dnf copr enable sneexy/zen-browser
sudo dnf copr enable lukenukem/asus-linux
sudo dnf copr enable errornointernet/quickshell
sudo dnf copr enable alternateved/eza
sudo dnf copr enable lihaohong/yazi
sudo dnf copr enable mcpengu1/viu 

sudo dnf update

