#!/bin/bash
echo "Installing Media-Related pkgs"
sleep 3
sudo dnf install alsa-utils pipewire pipewire-alsa pipewire-gstreamer pipewire-pulseaudio pipewire-utils pulseaudio-utils wireplumber mediainfo 
