#!/bin/bash
echo "Setting Up Selinux"
sleep 3
sudo dnf install setroubleshoot copr-selinux checkpolicy libsemanage libsepol libsepol-utils mcstrans policycoreutils policycoreutils-dbus policycoreutils-devel policycoreutils-gui policycoreutils-python-utils policycoreutils-restorecond policycoreutils-sandbox python3-policycoreutils python3-setools secilc secilc-doc selint sepolicy_analysis setools setools-console setools-console-analyses setools-gui setroubleshoot-server udica.noarch
