# Yazi Keymap Configuration
# This configuration provides vim-like navigation and file management keybindings

# Manager layer - File list navigation and operations
[[mgr.prepend_keymap]]
on = "h"
run = "leave"
desc = "Go back to parent directory"

[[mgr.prepend_keymap]]
on = "j"
run = "arrow 1"
desc = "Move cursor down"

[[mgr.prepend_keymap]]
on = "k"
run = "arrow -1"
desc = "Move cursor up"

[[mgr.prepend_keymap]]
on = "l"
run = "enter"
desc = "Enter directory"

[[mgr.prepend_keymap]]
on = [ "g", "g" ]
run = "arrow top"
desc = "Move cursor to top"

[[mgr.prepend_keymap]]
on = "G"
run = "arrow bot"
desc = "Move cursor to bottom"

[[mgr.prepend_keymap]]
on = [ "<C-d>" ]
run = "arrow 5"
desc = "Move cursor down 5 lines"

[[mgr.prepend_keymap]]
on = [ "<C-u>" ]
run = "arrow -5"
desc = "Move cursor up 5 lines"

[[mgr.prepend_keymap]]
on = [ "<C-f>" ]
run = "arrow 10"
desc = "Move cursor down 10 lines"

[[mgr.prepend_keymap]]
on = [ "<C-b>" ]
run = "arrow -10"
desc = "Move cursor up 10 lines"

# File operations
[[mgr.prepend_keymap]]
on = "y"
run = "yank"
desc = "Copy selected files"

[[mgr.prepend_keymap]]
on = "x"
run = "yank --cut"
desc = "Cut selected files"

[[mgr.prepend_keymap]]
on = "d"
run = "yank --cut"
desc = "Cut selected files"

[[mgr.prepend_keymap]]
on = "p"
run = "paste"
desc = "Paste files"

[[mgr.prepend_keymap]]
on = [ "d", "d" ]
run = "remove"
desc = "Remove selected files"

[[mgr.prepend_keymap]]
on = "v"
run = "visual_mode"
desc = "Enter visual mode"

[[mgr.prepend_keymap]]
on = "V"
run = "visual_mode --unset"
desc = "Enter visual mode (unset)"

[[mgr.prepend_keymap]]
on = "a"
run = "create"
desc = "Create new file or directory"

[[mgr.prepend_keymap]]
on = "r"
run = "rename --cursor=before_ext"
desc = "Rename selected file"

[[mgr.prepend_keymap]]
on = "u"
run = "undo"
desc = "Undo last operation"

[[mgr.prepend_keymap]]
on = [ "<C-r>" ]
run = "redo"
desc = "Redo last operation"

[[mgr.prepend_keymap]]
on = "c"
run = "cd --interactive"
desc = "Change directory"

[[mgr.prepend_keymap]]
on = "o"
run = "open"
desc = "Open file"

[[mgr.prepend_keymap]]
on = "O"
run = "open --interactive"
desc = "Open file interactively"

# Search and find
[[mgr.prepend_keymap]]
on = "/"
run = "find --smart"
desc = "Find files"

[[mgr.prepend_keymap]]
on = "n"
run = "find_arrow"
desc = "Go to next found file"

[[mgr.prepend_keymap]]
on = "N"
run = "find_arrow --previous"
desc = "Go to previous found file"

[[mgr.prepend_keymap]]
on = "f"
run = "filter --smart"
desc = "Filter files"

# Selection
[[mgr.prepend_keymap]]
on = "<Space>"
run = "toggle"
desc = "Toggle selection"

[[mgr.prepend_keymap]]
on = [ "<C-a>" ]
run = "toggle_all --state=on"
desc = "Select all files"

[[mgr.prepend_keymap]]
on = [ "g", "r" ]
run = "toggle_all --state=off"
desc = "Deselect all files"

[[mgr.prepend_keymap]]
on = [ "g", "t" ]
run = "toggle_all"
desc = "Toggle selection for all files"

# Tabs
[[mgr.prepend_keymap]]
on = "t"
run = "tab_create --current"
desc = "Create new tab"

[[mgr.prepend_keymap]]
on = "T"
run = "tab_close 0"
desc = "Close current tab"

[[mgr.prepend_keymap]]
on = "w"
run = "tab_close 0"
desc = "Close current tab"

[[mgr.prepend_keymap]]
on = [ "<C-t>" ]
run = "tab_create --current"
desc = "Create new tab"

[[mgr.prepend_keymap]]
on = [ "<C-w>" ]
run = "tab_close 0"
desc = "Close current tab"

[[mgr.prepend_keymap]]
on = "["
run = "tab_switch -1 --relative"
desc = "Switch to previous tab"

[[mgr.prepend_keymap]]
on = "]"
run = "tab_switch 1 --relative"
desc = "Switch to next tab"

[[mgr.prepend_keymap]]
on = [ "g", "T" ]
run = "tab_switch -1 --relative"
desc = "Switch to previous tab"

[[mgr.prepend_keymap]]
on = [ "g", "t" ]
run = "tab_switch 1 --relative"
desc = "Switch to next tab"

[[mgr.prepend_keymap]]
on = "{"
run = "tab_swap -1"
desc = "Swap current tab with previous"

[[mgr.prepend_keymap]]
on = "}"
run = "tab_swap 1"
desc = "Swap current tab with next"

# Tab switching with numbers
[[mgr.prepend_keymap]]
on = "1"
run = "tab_switch 0"
desc = "Switch to tab 1"

[[mgr.prepend_keymap]]
on = "2"
run = "tab_switch 1"
desc = "Switch to tab 2"

[[mgr.prepend_keymap]]
on = "3"
run = "tab_switch 2"
desc = "Switch to tab 3"

[[mgr.prepend_keymap]]
on = "4"
run = "tab_switch 3"
desc = "Switch to tab 4"

[[mgr.prepend_keymap]]
on = "5"
run = "tab_switch 4"
desc = "Switch to tab 5"

[[mgr.prepend_keymap]]
on = "6"
run = "tab_switch 5"
desc = "Switch to tab 6"

[[mgr.prepend_keymap]]
on = "7"
run = "tab_switch 6"
desc = "Switch to tab 7"

[[mgr.prepend_keymap]]
on = "8"
run = "tab_switch 7"
desc = "Switch to tab 8"

[[mgr.prepend_keymap]]
on = "9"
run = "tab_switch 8"
desc = "Switch to tab 9"

# Directory navigation
[[mgr.prepend_keymap]]
on = "~"
run = "cd ~"
desc = "Go to home directory"

[[mgr.prepend_keymap]]
on = "-"
run = "leave"
desc = "Go to parent directory"

# Miscellaneous
[[mgr.prepend_keymap]]
on = "q"
run = "quit"
desc = "Quit yazi"

[[mgr.prepend_keymap]]
on = "Q"
run = "quit --no-cwd-file"
desc = "Quit yazi without saving cwd"

[[mgr.prepend_keymap]]
on = ":"
run = "shell --interactive"
desc = "Run shell command"

[[mgr.prepend_keymap]]
on = "!"
run = "shell --block"
desc = "Run shell command and wait"

[[mgr.prepend_keymap]]
on = "?"
run = "help"
desc = "Show help"

[[mgr.prepend_keymap]]
on = "<Esc>"
run = "escape"
desc = "Exit current mode"

[[mgr.prepend_keymap]]
on = [ "<C-l>" ]
run = "refresh"
desc = "Refresh current directory"

[[mgr.prepend_keymap]]
on = [ "<C-h>" ]
run = "hidden toggle"
desc = "Toggle hidden files"

[[mgr.prepend_keymap]]
on = [ "<C-s>" ]
run = "spot"
desc = "Peek file content"

[[mgr.prepend_keymap]]
on = [ "<C-z>" ]
run = "suspend"
desc = "Suspend yazi"

[[mgr.prepend_keymap]]
on = "i"
run = "spot"
desc = "Inspect file"

[[mgr.prepend_keymap]]
on = "R"
run = "refresh"
desc = "Refresh current directory"

# Sorting
[[mgr.prepend_keymap]]
on = [ "s", "n" ]
run = "sort natural"
desc = "Sort naturally"

[[mgr.prepend_keymap]]
on = [ "s", "s" ]
run = "sort size"
desc = "Sort by size"

[[mgr.prepend_keymap]]
on = [ "s", "m" ]
run = "sort mtime"
desc = "Sort by modified time"

[[mgr.prepend_keymap]]
on = [ "s", "c" ]
run = "sort btime"
desc = "Sort by created time"

[[mgr.prepend_keymap]]
on = [ "s", "e" ]
run = "sort extension"
desc = "Sort by extension"

[[mgr.prepend_keymap]]
on = [ "s", "r" ]
run = "sort reverse"
desc = "Reverse sort order"

# Input mode keybindings
[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"

[[input.prepend_keymap]]
on = [ "<C-c>" ]
run = "close"
desc = "Cancel input"

[[input.prepend_keymap]]
on = [ "<C-n>" ]
run = "move 1"
desc = "Move cursor down in history"

[[input.prepend_keymap]]
on = [ "<C-p>" ]
run = "move -1"
desc = "Move cursor up in history"

[[input.prepend_keymap]]
on = [ "<C-f>" ]
run = "forward"
desc = "Move cursor forward"

[[input.prepend_keymap]]
on = [ "<C-b>" ]
run = "backward"
desc = "Move cursor backward"

[[input.prepend_keymap]]
on = [ "<C-a>" ]
run = "move -999"
desc = "Move cursor to start"

[[input.prepend_keymap]]
on = [ "<C-e>" ]
run = "move 999"
desc = "Move cursor to end"

[[input.prepend_keymap]]
on = [ "<C-u>" ]
run = "kill bol"
desc = "Kill from cursor to beginning of line"

[[input.prepend_keymap]]
on = [ "<C-k>" ]
run = "kill eol"
desc = "Kill from cursor to end of line"

[[input.prepend_keymap]]
on = [ "<C-w>" ]
run = "kill backward"
desc = "Kill word backward"

[[input.prepend_keymap]]
on = [ "<C-d>" ]
run = "delete"
desc = "Delete character forward"

[[input.prepend_keymap]]
on = [ "<C-h>" ]
run = "backspace"
desc = "Delete character backward"

[[input.prepend_keymap]]
on = "<Backspace>"
run = "backspace"
desc = "Delete character backward"

[[input.prepend_keymap]]
on = "<Delete>"
run = "delete"
desc = "Delete character forward"

[[input.prepend_keymap]]
on = "<Enter>"
run = "close --submit"
desc = "Submit input"

# Tasks mode keybindings
[[tasks.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Close task manager"

[[tasks.prepend_keymap]]
on = [ "<C-c>" ]
run = "close"
desc = "Close task manager"

[[tasks.prepend_keymap]]
on = "j"
run = "arrow 1"
desc = "Move cursor down"

[[tasks.prepend_keymap]]
on = "k"
run = "arrow -1"
desc = "Move cursor up"

[[tasks.prepend_keymap]]
on = "w"
run = "inspect"
desc = "Inspect task"

[[tasks.prepend_keymap]]
on = "c"
run = "cancel"
desc = "Cancel task"

# Help mode keybindings
[[help.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Close help"

[[help.prepend_keymap]]
on = [ "<C-c>" ]
run = "close"
desc = "Close help"

[[help.prepend_keymap]]
on = "j"
run = "arrow 1"
desc = "Move cursor down"

[[help.prepend_keymap]]
on = "k"
run = "arrow -1"
desc = "Move cursor up"

[[help.prepend_keymap]]
on = [ "<C-d>" ]
run = "arrow 5"
desc = "Move cursor down 5 lines"

[[help.prepend_keymap]]
on = [ "<C-u>" ]
run = "arrow -5"
desc = "Move cursor up 5 lines"

# Confirm mode keybindings
[[confirm.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel confirmation"

[[confirm.prepend_keymap]]
on = [ "<C-c>" ]
run = "close"
desc = "Cancel confirmation"

[[confirm.prepend_keymap]]
on = "j"
run = "arrow 1"
desc = "Move cursor down"

[[confirm.prepend_keymap]]
on = "k"
run = "arrow -1"
desc = "Move cursor up"

[[confirm.prepend_keymap]]
on = "<Enter>"
run = "close --submit"
desc = "Submit confirmation"

# Pick mode keybindings
[[pick.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel picker"

[[pick.prepend_keymap]]
on = [ "<C-c>" ]
run = "close"
desc = "Cancel picker"

[[pick.prepend_keymap]]
on = "j"
run = "arrow 1"
desc = "Move cursor down"

[[pick.prepend_keymap]]
on = "k"
run = "arrow -1"
desc = "Move cursor up"

[[pick.prepend_keymap]]
on = "<Enter>"
run = "close --submit"
desc = "Submit selection"

# Completion mode keybindings
[[cmp.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel completion"

[[cmp.prepend_keymap]]
on = [ "<C-c>" ]
run = "close"
desc = "Cancel completion"

[[cmp.prepend_keymap]]
on = "j"
run = "arrow 1"
desc = "Move cursor down"

[[cmp.prepend_keymap]]
on = "k"
run = "arrow -1"
desc = "Move cursor up"

[[cmp.prepend_keymap]]
on = "<Enter>"
run = "close --submit"
desc = "Submit completion"

# Spot mode keybindings
[[spot.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Close spotter"

[[spot.prepend_keymap]]
on = [ "<C-c>" ]
run = "close"
desc = "Close spotter"

[[spot.prepend_keymap]]
on = "j"
run = "arrow 1"
desc = "Move cursor down"

[[spot.prepend_keymap]]
on = "k"
run = "arrow -1"
desc = "Move cursor up"

[[spot.prepend_keymap]]
on = [ "<C-d>" ]
run = "arrow 5"
desc = "Move cursor down 5 lines"

[[spot.prepend_keymap]]
on = [ "<C-u>" ]
run = "arrow -5"
desc = "Move cursor up 5 lines"
