[mgr]
# Display and behavior
show_hidden = false
show_symlink = true
linemode = "size"
scrolloff = 5
mouse_events = ["click", "scroll"]  # Fixed: was mouse_support
title_format = "Yazi: {cwd}"

# Sorting
sort_by = "natural"
sort_dir_first = true
sort_reverse = false
sort_translit = false

# Selection and interaction
tab_size = 4
# Removed max_preview as it doesn't exist in manager section

[preview]
# Image preview settings
image_filter = "triangle"
image_quality = 75
max_width = 600
max_height = 900
cache_dir = ""

# Wrap settings
wrap = "no"
tab_size = 2

[opener]
# Text files
edit = [
    { run = 'nvim "$@"', desc = "Edit with Neovim", block = true },
    { run = 'vim "$@"', desc = "Edit with Vim", block = true },
    { run = 'code "$@"', desc = "Edit with VS Code" },
    { run = 'gedit "$@"', desc = "Edit with Gedit" },
]

# Archives
archive = [
    { run = 'file-roller "$@"', desc = "Open with File Roller" },
    { run = 'ark "$@"', desc = "Open with Ark" },
]

# Images
image = [
    { run = 'eog "$@"', desc = "Open with Eye of GNOME" },
    { run = 'gwenview "$@"', desc = "Open with Gwenview" },
    { run = 'feh "$@"', desc = "Open with Feh" },
]

# Videos
video = [
    { run = 'mpv "$@"', desc = "Play with mpv" },
    { run = 'vlc "$@"', desc = "Play with VLC" },
    { run = 'totem "$@"', desc = "Play with Totem" },
]

# Audio
audio = [
    { run = 'mpv "$@"', desc = "Play with mpv" },
    { run = 'rhythmbox "$@"', desc = "Play with Rhythmbox" },
]

# Documents
document = [
    { run = 'evince "$@"', desc = "Open with Evince" },
    { run = 'okular "$@"', desc = "Open with Okular" },
    { run = 'libreoffice "$@"', desc = "Open with LibreOffice" },
]

# Fallback
fallback = [
    { run = 'xdg-open "$@"', desc = "Open with default application" },
]

[open]
# Rules for opening files
rules = [
    { name = "*/", use = "edit" },
    { mime = "text/*", use = "edit" },
    { mime = "image/*", use = "image" },
    { mime = "video/*", use = "video" },
    { mime = "audio/*", use = "audio" },
    { mime = "application/pdf", use = "document" },
    { mime = "application/*zip", use = "archive" },
    { mime = "application/x-tar", use = "archive" },
    { mime = "application/x-bzip2", use = "archive" },
    { mime = "application/x-gzip", use = "archive" },
    { mime = "application/x-7z-compressed", use = "archive" },
    { name = "*", use = "fallback" },
]

[tasks]
# Task management
micro_workers = 5
macro_workers = 10
bizarre_retry = 5
image_alloc = 536870912  # 512MB
image_bound = [0, 0]
suppress_preload = false

# Removed [log] section as it's not a valid configuration section in current Yazi
